### ISSUE TITLE
onUnreadMessagesCountUpdated的调用问题

### ISSUE THREAD

**Issue by 451518849** [leancloud/java-unified-sdk#109]
AVIMConversationEventHandler中的onUnreadMessagesCountUpdated是只在登陆的时候调用一次获取所有的未读消息吗？如果当前处于会话列表是否能实时获取unreadMessage用于实时更新会话列表的未读数？

**Comment by jwfing** [comment]
SDK 内部有一个缓存，会把上次获取 unreadMessageCount 的时间戳记下来，下次再启动只会收到上一个时间戳之后变化了的记数。所以需要客户端内部把这个 unreadmessagecount 缓存下来。

**Comment by jwfing** [comment]
如果当前处于会话列表，那么消息一般都直接收到了，是不会再有未读消息的。另外，进入一个会话的时候，需要调用 read 方法来将当前回话的未读数清零。

**Comment by jwfing** [comment]
未读消息只有在客户端离线的时候，才会出现。只要打开着应用，我们后台的 PushService 没有被杀掉，消息就实时下发了。

**Comment by 451518849** [comment]
了解。的确是可以通过onMessage获取最新的消息用来更新会话列表的unreadmessagecount。
ios端对应的这个方法就能实时获取未读消息：
`
- (void)conversation:(AVIMConversation *)conversation didUpdateForKey:(AVIMConversationUpdatedKey)key 
`
这样可能会更方便刷新会话列表的unreadmessagecount。
