### ISSUE TITLE
对话自定义属性的时候，没用 attr 而是新增字段的时候，会话的自定义属性无法读取

### ISSUE THREAD

**Issue by SXiaoXu** [leancloud/java-unified-sdk#129]
Android sdk： 6.5.1

自定义属性的时候：
```
conversation.set("content", "这周周会改到周三下午三点。");
conversation.updateInfoInBackground(new AVIMConversationCallback(){
    @Override
    public void done(AVIMException e){
        if(e==null){
            // 更新成功
            Log.d("test","成功！");
        }else {
            Log.d("error:",e.getMessage());
        }
    }
});
```
**查询会话的时候拿不到这个 content**，查询会话返回的数据是这样的：
```
{"temp":false,"c":"Tom20200708","conv_type":1,"name":"Tom & Jerry","m":["Tom20200708","Jerry"],"tr":false,"objectId":"5f054666382fdc00081a0662"}
```

![image](https://user-images.githubusercontent.com/11917002/86880840-e185a300-c11f-11ea-8c0c-31ec30b36fb3.png)

在 iOS 是支持这样使用自定义属性的。

**Comment by jwfing** [comment]
这是因为 conversation 类从设计上就是通过 attr 来扩展属性的，不支持自定义一级属性。

**Comment by SXiaoXu** [comment]
当时一个用户问的，他们用 OC SDK 已经先这样用了，后来 Android 这边发现不能读取才过来咨询的。跟用户说了不支持这样新增属性了。

是不是应该在新建属性的时候就报错提示「不支持自定义一级属性」。

**Comment by weakish** [comment]
> 他们用 OC SDK 已经先这样用了，后来 Android 这边发现不能读取才过来咨询的

不科学啊，objc sdk 自定义属性应该也是写到 `attr` 里的呀 @zapcannon87

**Comment by zapcannon87** [comment]
> > 他们用 OC SDK 已经先这样用了，后来 Android 这边发现不能读取才过来咨询的
> 
> 不科学啊，objc sdk 自定义属性应该也是写到 `attr` 里的呀 @zapcannon87

创建会话时，会限制写到 `attr`；修改会话属性无限制。JS 那边应该也是类似的。都是历史问题，一开始设计时没限制住，现在就只能让已经这么用的用户继续使用了。

**Comment by zapcannon87** [comment]
历史上下文：
https://github.com/leancloud/rfcs/issues/846

@weakish 可以直接询问 @leeyeh

**Comment by leeyeh** [comment]
感觉这里还是有些误解，我试着澄清一下：

首先，User 也好，Conversation 也好，导致我们遇到了性能问题的是「允许用户扩展自定义属性」而不是「允许自定义一级属性」，把一个属性从一级属性改成二级属性也不能改善性能问题。

其次，实际上这个 `attr` 并没有任何特殊的地方，他只是早期 SDK 之间的一个约定，服务端没有任何层面真正限制了用户创建其他属性。而他其实并没有那么符合直觉（比如为什么是 `attr` 而不是 `attributes` 或者稍微更有意义一点的 `metaData`）。

所以我认为合理的做法应该是允许创建修改 Conversation 的一级属性。
