### ISSUE TITLE
protobuf lib Duplicate class

### ISSUE THREAD

**Issue by SeaZhang** [leancloud/java-unified-sdk#147]
when I compile the project, IDE throws an error:

**

> Duplicate class com.google.protobuf.AbstractMessageLite found in modules jetified-protobuf-java-3.9.1 (com.google.protobuf:protobuf-java:3.9.1) and jetified-protobuf-javalite-3.11.0 (com.google.protobuf:protobuf-javalite:3.11.0)

**

realtime-core reps :com.google.protobuf:protobuf-java:3.9.1   with  google firbase perf lib reps: com.google.protobuf:protobuf-javalite:3.11.0   has Duplicate classes.

can I config the reps lib protobuf-java by myself?

**Comment by jwfing** [comment]
yes, you can upgrade protobuf-java library version.

**Comment by SeaZhang** [comment]
Lean Cloud realtime-android  lib   and  google firebase perf lib:

|    +--- cn.leancloud:realtime-android:6.5.14
|    |    +--- cn.leancloud:storage-android:6.5.14
|    |    |    +--- io.reactivex.rxjava2:rxandroid:2.1.1 (*)
|    |    +--- cn.leancloud:realtime-core:6.5.14
|    |    |    +--- cn.leancloud:storage-core:6.5.14 (*)
|    |    |    +--- com.google.protobuf:protobuf-java:3.9.1

and

+--- com.google.firebase:firebase-perf -> 19.0.10
|    +--- androidx.annotation:annotation:1.1.0
|    +--- androidx.appcompat:appcompat:1.2.0 (*)
|    +--- com.google.android.datatransport:transport-api:2.2.1 (*)
|    +--- com.google.android.gms:play-services-base:17.3.0
|    |    +--- androidx.collection:collection:1.0.0 -> 1.1.0 (*)
|    |    +--- androidx.core:core:1.2.0 -> 1.3.0 (*)
|    |    +--- androidx.fragment:fragment:1.0.0 -> 1.1.0 (*)
|    |    +--- com.google.android.gms:play-services-basement:17.3.0 (*)
|    |    \--- com.google.android.gms:play-services-tasks:17.1.0 (*)
|    +--- com.google.android.gms:play-services-basement:17.3.0 (*)
|    +--- com.google.android.gms:play-services-clearcut:17.0.0
|    |    +--- androidx.core:core:1.0.0 -> 1.3.0 (*)
|    |    +--- com.google.android.gms:play-services-base:17.0.0 -> 17.3.0 (*)
|    |    +--- com.google.android.gms:play-services-basement:17.0.0 -> 17.3.0 (*)
|    |    +--- com.google.android.gms:play-services-phenotype:17.0.0
|    |    |    +--- androidx.core:core:1.0.0 -> 1.3.0 (*)
|    |    |    +--- com.google.android.gms:play-services-base:17.0.0 -> 17.3.0 (*)
|    |    |    +--- com.google.android.gms:play-services-basement:17.0.0 -> 17.3.0 (*)
|    |    |    \--- com.google.android.gms:play-services-tasks:17.0.0 -> 17.1.0 (*)
|    |    \--- com.google.android.gms:play-services-tasks:17.0.0 -> 17.1.0 (*)
|    +--- com.google.android.gms:play-services-tasks:17.1.0 (*)
|    +--- com.google.firebase:firebase-common:19.4.0 (*)
|    +--- com.google.firebase:firebase-components:16.0.0 -> 16.0.1 (*)
|    +--- com.google.firebase:firebase-config:20.0.1 -> 20.0.2
|    |    +--- com.google.android.gms:play-services-tasks:17.0.2 -> 17.1.0 (*)
|    |    +--- com.google.firebase:firebase-abt:20.0.0
|    |    |    +--- com.google.android.gms:play-services-basement:17.0.0 -> 17.3.0 (*)
|    |    |    +--- com.google.firebase:firebase-common:19.3.1 -> 19.4.0 (*)
|    |    |    +--- com.google.firebase:firebase-components:16.0.0 -> 16.0.1 (*)
|    |    |    \--- com.google.firebase:firebase-measurement-connector:18.0.0 (*)
|    |    +--- com.google.firebase:firebase-common:19.4.0 (*)
|    |    +--- com.google.firebase:firebase-components:16.0.0 -> 16.0.1 (*)
|    |    +--- com.google.firebase:firebase-installations:16.3.4 (*)
|    |    +--- com.google.firebase:firebase-installations-interop:16.0.0 (*)
|    |    \--- com.google.firebase:firebase-measurement-connector:18.0.0 (*)
|    +--- com.google.firebase:firebase-datatransport:17.0.9
|    |    +--- androidx.annotation:annotation:1.1.0
|    |    +--- com.google.android.datatransport:transport-api:2.2.1 (*)
|    |    +--- com.google.android.datatransport:transport-backend-cct:2.3.2 (*)
|    |    +--- com.google.android.datatransport:transport-runtime:2.2.5 (*)
|    |    +--- com.google.firebase:firebase-common:19.4.0 (*)
|    |    \--- com.google.firebase:firebase-components:16.0.0 -> 16.0.1 (*)
|    +--- com.google.firebase:firebase-installations:16.3.4 (*)
|    +--- com.google.firebase:firebase-installations-interop:16.0.0 (*)
|    +--- com.google.firebase:protolite-well-known-types:17.1.0
|    |    \--- com.google.protobuf:protobuf-javalite:3.11.0
|    +--- com.google.protobuf:protobuf-javalite:3.11.0

**Comment by jwfing** [comment]
You can exclude protobuf module from realtime-android(or core) as following:

```
    implementation("cn.leancloud:realtime-android:${sdkVersion}") {
        exclude group:'com.google.protobuf', module:'protobuf-java'
    }
```

and then add particular protobuf module again in build.gradle:
```
implementation 'com.google.protobuf:protobuf-javalite:3.11.0'
```

Hopefully it helps.
