### ISSUE TITLE
Java云函数解析参数错误？

### ISSUE THREAD

**Issue by wsxiaoys** [leancloud/java-unified-sdk#159]
https://github.com/leancloud/java-unified-sdk/blob/957961eb6415fbd43bd42242907bc4a449f154d1/leanengine/src/main/java/cn/leancloud/EngineFunctionParamInfo.java#L29

这里当`type`为AVObject子类时，会走line 31的code path: `Utils.getParsedObject(JSON.parseObject(content));`

而根据：https://github.com/leancloud/java-unified-sdk/blob/957961eb6415fbd43bd42242907bc4a449f154d1/core/src/main/java/cn/leancloud/ops/Utils.java#L152

因为此时的传入值`object`是`JSONObject`，所以`Utils.getParsedObject`的返回值总是一个`Map`.

似乎正确的做法是line 31修改成
```
return Utils.getObjectFrom(JSON.parseObject(content))
```

**Comment by wsxiaoys** [comment]
具体例子来说，比如`Document`为`AVObject`的子类，那么如果Document作为云函数参数会抛`IllegalArgumentException`。

但如果使用`List<Document>`作为云函数参数则能够正常使用List<Document>调用，因为此时走的路径是L36:
https://github.com/leancloud/java-unified-sdk/blob/957961eb6415fbd43bd42242907bc4a449f154d1/leanengine/src/main/java/cn/leancloud/EngineFunctionParamInfo.java#L36

**Comment by weakish** [comment]
`content` 是 String，如果这里不调用 `JSON.parseObject`，那最终就作为 Object 返回了，没有进行处理。调用 `JSON.parseObject` 才能被转成 HashMap。

请问您具体触发 `IllegalArgumentException` 的代码是什么样的（方便的话可以把相应的云函数定义和客户端调用云函数的代码都贴一下）

**Comment by wsxiaoys** [comment]
@weakish 调用JSON.parseObject没有问题。上面指出有问题的是`Utils.getParsedObject`

**Comment by weakish** [comment]
不好意思，看错了。parseParams 的逻辑确实有点绕，对符合规格的 Map 会返回一个 AVObject，但对 AVObject 反而会转成 Map，导致 `Document` 和 `List<Document>` 的行为不一致。请 @jwfing 看一下。

**Comment by jwfing** [comment]
确实有这个问题，内部都是转成了 map（JsonObject）在使用，我们尽快改掉。

**Comment by jwfing** [comment]
@wsxiaoys 感谢反馈！！
