### ISSUE TITLE
默认查询策略获取不到会话的创建时间 conversation.getCreatedAt()。

### ISSUE THREAD

**Issue by SXiaoXu** [leancloud/java-unified-sdk#172]
记录工单中遇到的问题： https://leanticket.cn/tickets/37756

ConversationsQuery 使用默认的查询策略。在应用打开的第一次查询走网络，第一次查询会话是能获取到 conversation.getCreatedAt()，第二次查询默认的策略是先走本地缓存的，这时候会获取不到 createdAt。

**Comment by jwfing** [comment]
在 8.0.0 中修复。
