### ISSUE TITLE
聊天删除不了本地缓存的消息

### ISSUE THREAD

**Issue by SXiaoXu** [leancloud/java-unified-sdk#177]
sdk:7.2.6

imConversation.removeFromLocalCache(message) 以后，queryMessagesFromCache 还能查到同一个消息。

用户工单： https://ticket.avosapps.us/tickets/256

**Comment by jwfing** [comment]
应该与调用方法有关，不是原来发送失败的消息，是不可以从缓存中删除的。

**Comment by jwfing** [comment]
用户用错方法了， removeFromLocalCache 函数说明是用来删除本地之前发送失败的消息的，他用来删除云端消息，所以肯定不行。
