### ISSUE TITLE
Reporting a security issue

### ISSUE THREAD

**Issue by artem-smotrakov** [leancloud/java-unified-sdk#180]
What would be the best way to report a security issue? Unfortunately, I can't find a security contact. It might be good to add a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository).

**Comment by weakish** [comment]
Hi, you can report security bugs by emailing the lead maintainer @jfeng directly at jfeng@leancloud.rocks.
Alternatively, you can report security bugs to ask@leancloud.rocks.

Thanks.
