### ISSUE TITLE
Potential timing attacks against cookie validation

### ISSUE THREAD

**Issue by artem-smotrakov** [leancloud/java-unified-sdk#186]
After discussing this with @jwfing, agreed to disclose it and open a pull request with a fix. Below is the original report.

This is a follow-up on https://github.com/leancloud/java-unified-sdk/issues/180

I came across java-unified-sdk project, and noticed that `DefaultLCUserCookieSign.validateCookieSign()` method uses `String.equals()` for validating MAC over a cookie:

https://github.com/leancloud/java-unified-sdk/blob/30f9ee81b6b9ab0bc98dfa27c756435769cb7e5e/leanengine/src/main/java/cn/leancloud/impl/DefaultLCUserCookieSign.java#L107

`String.equals()` doesn't implement a constant-time algorithm for comparing inputs. As a result, an attacker may be able to run a timing attack that can forge a MAC for an arbitrary cookie. In turn, that would allow them to bypass this check

https://github.com/leancloud/java-unified-sdk/blob/ff841ae216d423444b8682a388137cae71253bd3/leanengine/src/main/java/cn/leancloud/EngineSessionCookie.java#L38

Looks like an authentication bypass. Unfortunately, I am not familiar with the project, so currently I can't estimate the possible impact. One thing I noticed is that data from the cookie is supposed to be deserialized in the `decodeUser()` method after a successful signature check:

https://github.com/leancloud/java-unified-sdk/blob/30f9ee81b6b9ab0bc98dfa27c756435769cb7e5e/leanengine/src/main/java/cn/leancloud/impl/DefaultLCUserCookieSign.java#L45

The `JSON.parseObject(userInfoStr, Map.class)` call may result in deserializing arbitrary data from a malicious cookie. Depending on the deserialization library under the hood, this can be relatively safe or result in arbitrary code execution in the worse case.

It is better to use `MessageDigest.isEqual()` for checking MACs. The following patch fixes the issue:

```
diff --git a/leanengine/src/main/java/cn/leancloud/impl/DefaultLCUserCookieSign.java b/leanengine/src/main/java/cn/leancloud/impl/DefaultLCUserCookieSign.java
index ea737bf8..9ea21a1b 100644
--- a/leanengine/src/main/java/cn/leancloud/impl/DefaultLCUserCookieSign.java
+++ b/leanengine/src/main/java/cn/leancloud/impl/DefaultLCUserCookieSign.java
@@ -4,6 +4,7 @@ import cn.leancloud.*;
 import cn.leancloud.utils.LogUtil;
 import cn.leancloud.json.JSON;
 
+import java.security.MessageDigest;
 import javax.crypto.Mac;
 import javax.crypto.spec.SecretKeySpec;
 import javax.servlet.http.Cookie;
@@ -104,7 +105,9 @@ public class DefaultLCUserCookieSign implements LCUserCookieSign {
             && userCookie.getValue() != null) {
       try {
         String encryptedCookieValue = encrypt(secret, sessionKey + "=" + userCookie.getValue());
-        return cookieSign.getValue().equals(encryptedCookieValue);
+        return MessageDigest.isEqual(
+            cookieSign.getValue().getBytes(),
+            encryptedCookieValue.getBytes());
       } catch (Exception e) {
 
       }
```

I can open a pull request if you think the problems can be disclosed. Alternatively, you can create a security advisory and a private branch on GitHub. Then, I can open a private pull request against the private branch. Or, just feel free to apply/modify the patch.

**Comment by jwfing** [comment]
@artem-smotrakov Thank you!
