### ISSUE TITLE
开启手机日志 密钥也会打印进入

### ISSUE THREAD

**Issue by lkrun** [leancloud/java-unified-sdk#216]
dependencies {
  compile 'org.slf4j:slf4j-api:1.7.25'
  compile 'com.github.tony19:logback-android:2.0.0'
}

导入这个日志框架，自己的密钥也会打印进去，，，，，

还有救吗

**Comment by jwfing** [comment]
你说的密钥是 appKey，还是 appId？

**Comment by jwfing** [comment]
appid 是公开的，会打印到日志里，但是 appkey 我们是不会打印出来的。
