### ISSUE TITLE
发送失败的消息未保存？

### ISSUE THREAD

**Issue by uni7corn** [leancloud/java-unified-sdk#229]
前置条件：由于网络原因，消息发送失败，退出会话，然后再进入

实际结果：发现发送失败的消息不存在了

期望值：发送失败的消息，也应该存在于该会话中，即该会话的消息列表中

我查看了sdk代码，发现sdk 设计时，就没先本地缓存该消息，而是发送成功之后再存储该条消息
即，sdk 注释所说，先发送一条暂存消息。请问这样设计，处于什么考虑！

[](url
<img width="1018" alt="截屏2022-08-16 15 51 07" src="https://user-images.githubusercontent.com/8399829/184828466-97ed383d-c60a-469e-90fd-43e2fd90f4cb.png">
)

**Comment by uni7corn** [comment]
<img width="850" alt="截屏2022-08-16 16 12 36" src="https://user-images.githubusercontent.com/8399829/184830983-d5b97044-0de2-41ee-b05e-15871cccb596.png">

**Comment by jwfing** [comment]
发送失败的消息，需要调用专门的接口缓存起来：
conversation#addToLocalCache
具体可参看文档：https://leancloud.cn/docs/realtime-guide-intermediate.html#hash-1066307453
