### ISSUE TITLE
gson 升级到 0.9.1 后初始化崩溃

### ISSUE THREAD

**Issue by LinXueyuanStdio** [leancloud/java-unified-sdk#231]

**Comment by jwfing** [comment]
那是因为我们 SDK 底层依赖的 gson 版本是 0.8.9，gson 不同版本之间不兼容，暂时还需要应用层固定 gson 版本到 0.8。

**Comment by LinXueyuanStdio** [comment]
1. 有计划提高 gson 版本么？
2. 有计划提供 json 解析的自定义接口么？这样可以去掉 gson
