### ISSUE TITLE
ANR问题

### ISSUE THREAD

**Issue by zhoujunyou** [leancloud/java-unified-sdk#59]
接入后cn.leancloud.push.PushService和com.xiaomi.mipush.sdk.PushMessageHandler偶现ANR
依赖版本：implementation('cn.leancloud:storage-android:5.0.15')
    implementation('cn.leancloud:realtime-android:5.0.15') {
        exclude group: 'com.alibaba', module: 'fastjson'
        exclude group: 'org.ligboy.retrofit2', module: 'converter-fastjson'
    }
Application OnCreate中调用PushService.startIfRequired(this);

日志：2019-07-17 09:38:32.898 30645-30645 D/PushService: PushService#onCreate
2019-07-17 09:38:32.902 30645-30645 D/PushService: PushService#onStartCommand
2019-07-17 09:38:32.903 30645-30645 D/PushService: networking is fine and try to start connection to leancloud.
2019-07-17 09:38:32.903 30645-30645 D/AVConnectionManager: start connection with callback...
2019-07-17 09:38:32.903 30645-30913 D/AVConnectionManager: start connection...
2019-07-17 09:38:32.910 30645-30645/com.test.app D/AppRouter: fetchRTMServerFromRemote. router=https://router-g0-push.avoscloud.com, appId=gA9kYQrjG3peavRdQ0MsNdCa-gzGzoHsz
2019-07-17 09:38:32.915 30645-30913/com.test.app D/AppRouter: fetchRTMServerFromRemote. router=https://router-g0-push.avoscloud.com, appId=gA9kYQrjG3peavRdQ0MsNdCa-gzGzoHsz
2019-07-17 09:38:32.923 752-822/? E/ANDR-PERF-OPTSHANDLER: perf_lock_rel: updated /sys/class/mmc_host/mmc0/clk_scaling/enable with 1

ANR信息：
2019-07-17 09:38:55.340 1840-1884/? E/ActivityManager: ANR in com.test.app
    PID: 30645
    Reason: executing service com.test.app/com.xiaomi.mipush.sdk.PushMessageHandler
    Load: 0.0 / 0.0 / 0.0
    CPU usage from 41483ms to 0ms ago (2019-07-17 09:38:11.460 to 2019-07-17 09:38:52.943):
      11% 1840/system_server: 8.9% user + 2.6% kernel / faults: 19566 minor
      3.5% 2254/com.android.systemui: 2.5% user + 0.9% kernel / faults: 9542 minor 1 major
      3.3% 772/surfaceflinger: 2.5% user + 0.7% kernel / faults: 56 minor
      2.3% 742/android.hardware.sensors@1.0-service: 0.5% user + 1.7% kernel
      1.4% 582/logd: 0.5% user + 0.9% kernel / faults: 5 minor
      1.2% 736/android.hardware.graphics.composer@2.1-service: 0.7% user + 0.4% kernel / faults: 9 minor
      1.1% 4368/com.miui.powerkeeper: 0.4% user + 0.6% kernel / faults: 130 minor
      1.1% 26037/adbd: 0.1% user + 1% kernel / faults: 2920 minor
      1.1% 27865/com.tencent.mm: 0.8% user + 0.2% kernel / faults: 992 minor
      1% 13415/com.miui.home: 0.8% user + 0.2% kernel / faults: 5068 minor
      0.7% 25316/kworker/u16:2: 0% user + 0.7% kernel
      0.7% 19112/kworker/u16:6: 0% user + 0.7% kernel
      0.5% 27352/kworker/u16:9: 0% user + 0.5% kernel
      0.4% 27298/kworker/u16:3: 0% user + 0.4% kernel
      0.4% 27445/mdss_fb0: 0% user + 0.4% kernel
      0.4% 30479/logcat: 0.1% user + 0.2% kernel / faults: 2 minor
      0.3% 93/system: 0% user + 0.3% kernel
      0.3% 2551/com.android.phone: 0% user + 0.2% kernel / faults: 169 minor
      0.3% 13450/com.tencent.mobileqq:MSF: 0.3% user + 0% kernel / faults: 77 minor
      0.2% 3019/com.xiaomi.xmsf: 0.2% user + 0% kernel / faults: 676 minor
      0.2% 291/kgsl_worker_thr: 0% user + 0.2% kernel
      0.2% 583/servicemanager: 0% user + 0.1% kernel
      0.2% 25301/kworker/u17:0: 0% user + 0.2% kernel
      0.2% 27249/kworker/u17:1: 0% user + 0.2% kernel
      0.2% 28749/kworker/u17:3: 0% user + 0.2% kernel
      0.1% 735/android.hardware.graphics.allocator@2.0-service: 0% user + 0.1% kernel / faults: 75 minor
      0.1% 1245/thermal-engine: 0% user + 0.1% kernel
      0.1% 1253/zygote64: 0% user + 0.1% kernel / faults: 949 minor
      0% 1300/android.hardware.biometrics.fingerprint@2.1-service: 0% user + 0% kernel / faults: 221 minor
      0.1% 17811/kworker/0:2: 0% user + 0.1% kernel
      0.1% 15/ksoftirqd/1: 0% user + 0.1% kernel
      0.1% 447/mmc-cmdqd/0: 0% user + 0.1% kernel
      0.1% 1272/netd: 0% user + 0% kernel / faults: 322 minor
      0.1% 5998/com.baidu.input_mi: 0% user + 0% kernel / faults: 46 minor
      0.1% 12456/irq/61-1008000.: 0% user + 0.1% kernel
      0% 79/smem_native_rpm: 0% user + 0% kernel
      0% 741/android.hardware.power@1.0-service: 0% user + 0% kernel
      0% 752/vendor.qti.hardware.perf@1.0-service: 0% user + 0% kernel / faults: 52 minor
      0% 1234/jbd2/dm-1-8: 0% user + 0% kernel
      0% 1255/zygote: 0% user + 0% kernel / faults: 531 minor
      0% 1482/msm_irqbalance: 0% user + 0% kernel
      0% 24776/com.tencent.mobileqq: 0% user + 0% kernel / faults: 31 minor
      0% 27350/kworker/u16:4: 0% user + 0% kernel
      0% 27509/irq/265-synapti: 0% user + 0% kernel
      0% 2830/mcd: 0% user + 0% kernel
      0% 2979/com.miui.daemon: 0% user + 0% kernel / faults: 108 minor
      0% 20329/iptables-restore: 0% user + 0% kernel / faults: 106 minor
      0% 29914/kworker/1:3: 0% user + 0% kernel
      0% 3/ksoftirqd/0: 0% user + 0% kernel
      0% 7/rcu_preempt: 0% user + 0% kernel
      0% 10/rcuop/0: 0% user + 0% kernel
      0% 18/rcuop/1: 0% user + 0% kernel
      0% 39/rcuop/4: 0% user + 0% kernel
      0% 75/smem_native_lpa: 0% user + 0% kernel
      0% 76/lpass_smem_glin: 0% user + 0% kernel
      0% 441/cfinteractive: 0% user + 0% kernel
      0% 552/ueventd: 0% user + 0% kernel
      0% 862/mm-pp-dpps: 0% user + 0% kernel
      0% 1458/msm_thermal:fre: 0% user + 0% kernel
      0% 1498/ipacm: 0% user + 0% kernel
      0% 2992/com.android.nfc: 0% user + 0% kernel / faults: 332 minor
      0% 5563/kworker/u17:2: 0% user + 0% kernel
      0% 20330/ip6tables-restore: 0% user + 0% kernel / faults: 127 minor
      0% 8/rcu_sched: 0% user + 0% kernel
      0% 22/ksoftirqd/2: 0% user + 0% kernel
      0% 25/rcuop/2: 0% user + 0% kernel
      0% 29/ksoftirqd/3: 0% user + 0% kernel
      0% 46/rcuop/5: 0% user + 0% kernel
      0% 49/migration/6: 0

看日志AVConnectionManager的connecting字段并没有限制住两次startConnectionInternal，
而且在onStartCommond中去开启连接时startConnectionInternal中的appRouter.fetchRTMConnectionServer(routerHost, AVOSCloud.getApplicationId(), installationId,
                        1, retryConnectionCount < 1).blockingFirst();中的blockingFirst()会在主线程中调用await().

**Comment by liaolintao** [comment]
```
public class AVOSCloud extends cn.leancloud.core.AVOSCloud {
  public static void initialize(Context context, String appId, String appKey) {
    AppConfiguration.config(true, new AppConfiguration.SchedulerCreator() {
      public Scheduler create() {
        return AndroidSchedulers.mainThread();
      }
    });
}
}
```
其实这个问题是因为observerOn默认配的主线程;
我尝试不切换observerOn, 大部分情况都解决了, 但是今天又出现了, 应该是进程重启后没有走我的初始化;
`AppConfiguration.config(true, null);`
建议直接默认的observerOn不要配成主线程;
我看了你的改动, 感觉不需要那样改; @juvenn

**Comment by jwfing** [comment]
您升级到 5.0.23 版本试一下呢？
