### ISSUE TITLE
即时通讯签名怎么处理

### ISSUE THREAD

**Issue by dajiba666** [leancloud/java-unified-sdk#61]
现在云函数全是异步 签名那个方法是同步的没法回调了

https://forum.avoscloud.com/t/java-unified-sdk/20750

**Comment by SXiaoXu** [comment]
https://forum.avoscloud.com/t/java-unified-sdk/20750

**Comment by dajiba666** [comment]
> https://forum.avoscloud.com/t/java-unified-sdk/20750
。。。这个就是我发的 我就是问现在没同步的回调了 要怎么搞

**Comment by jwfing** [comment]
您可以在 createSignature 方法中同步等待结果的，因为这本身也是在一个独立的线程中执行的，不影响主线程。
