### ISSUE TITLE
为什么AVobject返回的create是字符串类型 没法转

### ISSUE THREAD

**Issue by dajiba666** [leancloud/java-unified-sdk#62]
格式是这样 "createdAt" -> "2019-07-24T08:57:57.191Z"  感觉像是直接date.toString()

**Comment by weakish** [comment]
StringUtil 类里提供了一个静态方法 dateFromString，可以将其转换为 Date

**Comment by dajiba666** [comment]
哦哦找到了

> 因为 LeanCloud 云端 createdAt 和 updatedAt 存的就是 UTC 时间戳字符串，而不是 Date 类型数据。
> 
> StringUtil 类里提供了一个静态方法 dateFromString，可以将其转换为 Date

找到了 感谢

**Comment by dajiba666** [comment]
> 因为 LeanCloud 云端 createdAt 和 updatedAt 存的就是 UTC 时间戳字符串，而不是 Date 类型数据。
> 
> StringUtil 类里提供了一个静态方法 dateFromString，可以将其转换为 Date

找到了 感谢
