### ISSUE TITLE
问一下，以下库你们还在支持更新吗

### ISSUE THREAD

**Issue by a542120974** [leancloud/java-unified-sdk#63]
cn.leancloud.android:avoscloud-sdk:v4.7.6
cn.leancloud.android:avoscloud-push:v4.7.6@aar
cn.leancloud.android:avoscloud-mixpush:v4.7.6@aar

我们项目比较老，问下这几个库还有在更新吗

**Comment by jwfing** [comment]
不支持了，老的 android sdk 现在统一版本为 4.7.15
