### ISSUE TITLE
用户反馈

### ISSUE THREAD

**Issue by AndyGu** [leancloud/java-unified-sdk#66]
请问集成了新版的sdk后，原先的反馈组件要如何集成？

**Comment by jwfing** [comment]
用户反馈请转移到「数据存储」中，用存储 API 自行实现。以后我们也会按照这种方式来处理现有的用户反馈组件。

**Comment by AndyGu** [comment]
@jwfing 请问下在2019 年 9 月底停止维护之后，原来集成的反馈组件是否还能使用，还是说要在此之前更新，感谢解答~

**Comment by jwfing** [comment]
停止维护之后，原来的 SDK 还是可用的，只是如果出现 bugfix 或者新加功能，都不会在老的 SDK 代码上进行更新了。
