### ISSUE TITLE
官网SDK说明有误，导致pom更新不下来包

### ISSUE THREAD

**Issue by legend91325** [leancloud/java-unified-sdk#69]
![1566530269(1)](https://user-images.githubusercontent.com/7420287/63564480-cbb6d000-c597-11e9-8377-65afa292e09d.png)
官网的 maven地址 写错了groupId ，导致尝试多次更新不下来，最后来到源码这里才发现。这个小错误，可能导致新用户 放弃了尝试。

**Comment by SXiaoXu** [comment]
抱歉，我们稍后会更新文档，感谢您的反馈。
