### ISSUE TITLE
华为混合推送接入报重复包错误

### ISSUE THREAD

**Issue by zhouwangzhen** [leancloud/java-unified-sdk#79]
implementation ('cn.leancloud:storage-android:6.0.4'){
        exclude group: 'com.alibaba', module: 'fastjson'
        exclude group: 'org.ligboy.retrofit2', module: 'converter-fastjson'
    }
    //混合推送需要的包
    implementation('cn.leancloud:mixpush-android:6.0.4@aar') {
        exclude group: 'com.alibaba', module: 'fastjson'
        exclude group: 'org.ligboy.retrofit2', module: 'converter-fastjson'
        exclude group: 'cn.leancloud', module:'huawei-hmsagent'
    }
    //即时通信与推送需要的包
    implementation ('cn.leancloud:realtime-android:6.0.4'){
        exclude group: 'com.alibaba', module: 'fastjson'
        exclude group: 'org.ligboy.retrofit2', module: 'converter-fastjson'
    }
    implementation 'com.alibaba:fastjson:1.1.70.android'
    implementation "org.ligboy.retrofit2:converter-fastjson-android:2.1.0"
    // 华为推送
    implementation 'com.huawei.android.hms:push:2.6.3.306'

在已经去掉com.huawei.android.hms:base:2.6.3.306的情况下报重复包错误
> Duplicate class com.huawei.hianalytics.a.a found in modules HiAnalyticsSDK_2.1.4.301.jar (com.huawei.android.hms:base:2.6.3.306) and hmssdk-2.6.3.306.jar (cn.leancloud:mixpush-android:6.0.4)
Duplicate class com.huawei.hianalytics.a.b found in modules HiAnalyticsSDK_2.1.4.301.jar (com.huawei.android.hms:base:2.6.3.306) and hmssdk-2.6.3.306.jar (cn.leancloud:mixpush-android:6.0.4)
....

**Comment by jwfing** [comment]
你应该是本地 libs 目录下包含了 hmssdk-2.6.3.306.jar 文件。如果本地有这个 jar 的话，就不要通过 aar  方式依赖 mixpush-android，直接使用 jar 来依赖即可。

**Comment by zhouwangzhen** [comment]
已经通过工单解决，删除了'com.huawei.android.hms:push:2.6.3.306'
