### ISSUE TITLE
String字符串转成AVObject对象发生报错

### ISSUE THREAD

**Issue by SXiaoXu** [leancloud/java-unified-sdk#90]
社区问题：https://forum.avoscloud.com/t/string-avobject/21771

**Comment by jwfing** [comment]
这是 fastjson 依赖版本不对导致的。

在 Android 上面，请使用如下依赖：
implementation 'com.alibaba:fastjson:1.1.70.android'

如果是纯 java 平台，我们 storage-core 依赖的的 fastjson 版本是 1.2.60
