### ISSUE TITLE
AVObject getDate 报错，App 崩溃

### ISSUE THREAD

**Issue by SXiaoXu** [leancloud/java-unified-sdk#93]
SDK 版本号：6.1.6

AVUser.getCurrentUser().getDate("createdAt")
发生错误 'java.lang.ClassCastException' exception.

AVObject getDate("createdAt") 获取createdAt updateAt 都会报错。

**Comment by jwfing** [comment]
这是返回的数据格式错了。

**Comment by jwfing** [comment]
@SXiaoXu 有可以复现的代码吗？

**Comment by jwfing** [comment]
createdAt updatedAt server 端返回的是 字符串， SDK 内部在 getUpdatedAt/getCreatedAt 中做了转换，才给 app 返回了 Date。如果直接通过 getxxx 获取，就是拿到原始值。

**Comment by SXiaoXu** [comment]
https://leanticket.cn/tickets/22647

**Comment by jwfing** [comment]
新版本相比老版本对类型做了更严格的限定，所以这种 int/string 强转 Date 的都会出错，我还是做一下兼容吧。

**Comment by jwfing** [comment]
6.1.8 中进行了兼容处理。
